on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: collect_metadata

jobs:
  collect:
    runs-on: ubuntu-20.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      emf_database_host: ${{ secrets.EMF_DATABASE_HOST }}
      emf_database_user: ${{ secrets.EMF_DATABASE_USER}}
      emf_database_pass: ${{ secrets.EMF_DATABASE_PASS}}
      emf_database: ${{ secrets.EMF_DATABASE}}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install packages
        run: |
          R -e install.packages('remotes')
          R -e remotes::install_github('emf-creaf/EMFtoolbox')

      - name: Collect metadata and update db
        run: |
          R -e EMFtoolbox::collect_metadata()
