on:
  push:
    paths:
      - '**.Rmd'

name: render_workflows_artifacts

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install packages
        run: |
          R -e 'install.packages("rmarkdown")'

      - name: Render Rmarkdown files
        run: |
          mkdir rendered_artifact
          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f, "html_fragment", "rendered_artifact/fragment.html")' ${RMD_PATH[*]}
      
      - uses: actions/upload-artifact@v2
        with:
          name: rendered_fragment
          path: rendered_artifact/